version: '3.3'

services:
  react-app:
    build: 
      context: ./client
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - node-app
  
  node-app:
    build: 
      context: ./server
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - NODE_ENV=production
    restart: always
